# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import OnlineShop_pb2 as OnlineShop__pb2


class ThingsSearcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListClothes = channel.unary_unary(
                '/ThingsSearcher/ListClothes',
                request_serializer=OnlineShop__pb2.TypeThing.SerializeToString,
                response_deserializer=OnlineShop__pb2.Answer.FromString,
                )


class ThingsSearcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListClothes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ThingsSearcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListClothes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClothes,
                    request_deserializer=OnlineShop__pb2.TypeThing.FromString,
                    response_serializer=OnlineShop__pb2.Answer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ThingsSearcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ThingsSearcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListClothes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ThingsSearcher/ListClothes',
            OnlineShop__pb2.TypeThing.SerializeToString,
            OnlineShop__pb2.Answer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
