# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OnlineShop.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10OnlineShop.proto\"G\n\tTypeThing\x12\x10\n\x08sub_name\x18\x01 \x01(\t\x12\x13\n\x0blower_price\x18\x02 \x01(\x05\x12\x13\n\x0bupper_price\x18\x03 \x01(\x05\"\x1f\n\x06\x41nswer\x12\x15\n\rnumber_things\x18\x01 \x01(\x05\x32\x36\n\x0eThingsSearcher\x12$\n\x0bListClothes\x12\n.TypeThing\x1a\x07.Answer\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OnlineShop_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPETHING._serialized_start=20
  _TYPETHING._serialized_end=91
  _ANSWER._serialized_start=93
  _ANSWER._serialized_end=124
  _THINGSSEARCHER._serialized_start=126
  _THINGSSEARCHER._serialized_end=180
# @@protoc_insertion_point(module_scope)
